### ISSUE TITLE
Motion sensor data

### ISSUE THREAD

**Issue by strunker** [alexa-samples/skill-sample-python-smarthome-switch#2]
Any chance of getting some type of sample for motion sensors? 

I am trying to understand how to programmatically access motion sensor data for sensors I have already configured. 

Much of the smart home docs go over how to configure a smart home device (if you are the manufacturer\creator). I am simply trying to access the motion sensor data, similar to how a routing can, and then take action on it. For example, imagine a Lambda function that is called when motion is sensed, or even if we can poll for this info somehow. 

The virtual switch samples are great, but I cant really find a succinct answer to the above.

**Comment by mikemaas-amazon** [comment]
Hello, I don't think your question can be answered here. The documentation and sample code are written from the perspective of implementing the sensor endpoint. Your comment that the documentation is aligned to the skill/endpoint manufacturer is correct. As such, there is no current way to access data from a 3rd party skill unless they share it through another API or other mechanism. In short, there is no direct access to motion sensor data for a skill or endpoint you have not created.
