### ISSUE TITLE
Discover Devices not found any device 

### ISSUE THREAD

**Issue by minensh1291** [alexa-samples/skill-sample-python-smarthome-switch#3]
Successfully test lambda and follow all steps, but at last not able to see Discover Device.

On Enebling Skill trigger lamnda and send response.
{
    "event": {
        "header": {
            "namespace": "Alexa.Authorization",
            "name": "AcceptGrant.Response",
            "messageId": "3e6ac365-ad30-4ecc-aac8-fd4c638e2c13",
            "payloadVersion": "3"
        },
        "payload": {}
    }
}

But on  Discover Device no Lmabda trigger.

**Comment by mikemaas-amazon** [comment]
Are you handling the Alexa.Discovery interface? https://developer.amazon.com/docs/device-apis/alexa-discovery.html

**Comment by kartikeya-rana** [comment]
Hi, 

I'm facing the same issue, unable to discover any device.  
Following is my directiveDiscovery response I got from Lambda Test.

```
{
  "event": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover.Response",
      "messageId": "57949dd5-da80-4536-87d6-90c0a3971e2f",
      "payloadVersion": "3"
    },
    "payload": {
      "endpoints": [
        {
          "capabilities": [
            {
              "type": "AlexaInterface",
              "interface": "Alexa",
              "version": "3"
            },
            {
              "type": "AlexaInterface",
              "interface": "Alexa.PowerController",
              "version": "3",
              "properties": {
                "supported": [
                  {
                    "name": "powerState"
                  }
                ],
                "proactivelyReported": false,
                "retrievable": false
              }
            }
          ],
          "description": "Sample Endpoint Description",
          "displayCategories": [
            "OTHER"
          ],
          "endpointId": "sample-switch-01",
          "friendlyName": "Sample Switch",
          "manufacturerName": "Sample Manufacturer"
        }
      ]
    }
  }
}
```

What should I do ?

**Comment by ddmakadia1699** [comment]
Same here I didn't get any devices in my devices list.
Lambda Test result :
`{
  "event": {
    "header": {
      "namespace": "Alexa.Discovery",
      "name": "Discover.Response",
      "messageId": "d80b1afc-c0f2-4851-b0fa-f1d0c58f3650",
      "payloadVersion": "3"
    },
    "payload": {
      "endpoints": [
        {
          "capabilities": [
            {
              "type": "AlexaInterface",
              "interface": "Alexa",
              "version": "3"
            },
            {
              "type": "AlexaInterface",
              "interface": "Alexa.PowerController",
              "version": "3",
              "properties": {
                "supported": [
                  {
                    "name": "powerState"
                  }
                ],
                "proactivelyReported": false,
                "retrievable": false
              }
            }
          ],
          "description": "Sample Endpoint Description",
          "displayCategories": [
            "OTHER"
          ],
          "endpointId": "sample-switch-01",
          "friendlyName": "Sample Switch",
          "manufacturerName": "Sample Manufacturer"
        }
      ]
    }
  }
}` 

Log Output : 
START RequestId: 4e58a2b4-480f-40c3-b77c-8eeaba33bf31 Version: $LATEST
lambda_handler request  -----
{"directive": {"header": {"namespace": "Alexa.Discovery", "name": "Discover", "payloadVersion": "3", "messageId": "1bd5d003-31b9-476f-ad03-71d471922820"}, "payload": {"scope": {"type": "BearerToken", "token": "access-token-from-skill"}}}}
lambda_handler context  -----
<__main__.LambdaContext object at 0x7f5c20dc9320>
lambda_handler response -----
{"event": {"header": {"namespace": "Alexa.Discovery", "name": "Discover.Response", "messageId": "d80b1afc-c0f2-4851-b0fa-f1d0c58f3650", "payloadVersion": "3"}, "payload": {"endpoints": [{"capabilities": [{"type": "AlexaInterface", "interface": "Alexa", "version": "3"}, {"type": "AlexaInterface", "interface": "Alexa.PowerController", "version": "3", "properties": {"supported": [{"name": "powerState"}], "proactivelyReported": false, "retrievable": false}}], "description": "Sample Endpoint Description", "displayCategories": ["OTHER"], "endpointId": "sample-switch-01", "friendlyName": "Sample Switch", "manufacturerName": "Sample Manufacturer"}]}}}
END RequestId: 4e58a2b4-480f-40c3-b77c-8eeaba33bf31
REPORT RequestId: 4e58a2b4-480f-40c3-b77c-8eeaba33bf31	Duration: 0.63 ms	Billed Duration: 100 ms	Memory Size: 128 MB	Max Memory Used: 64 MB

**Comment by ddmakadia1699** [comment]
> Hi,
> 
> I'm facing the same issue, unable to discover any device.
> Following is my directiveDiscovery response I got from Lambda Test.
> 
> ```
> {
>   "event": {
>     "header": {
>       "namespace": "Alexa.Discovery",
>       "name": "Discover.Response",
>       "messageId": "57949dd5-da80-4536-87d6-90c0a3971e2f",
>       "payloadVersion": "3"
>     },
>     "payload": {
>       "endpoints": [
>         {
>           "capabilities": [
>             {
>               "type": "AlexaInterface",
>               "interface": "Alexa",
>               "version": "3"
>             },
>             {
>               "type": "AlexaInterface",
>               "interface": "Alexa.PowerController",
>               "version": "3",
>               "properties": {
>                 "supported": [
>                   {
>                     "name": "powerState"
>                   }
>                 ],
>                 "proactivelyReported": false,
>                 "retrievable": false
>               }
>             }
>           ],
>           "description": "Sample Endpoint Description",
>           "displayCategories": [
>             "OTHER"
>           ],
>           "endpointId": "sample-switch-01",
>           "friendlyName": "Sample Switch",
>           "manufacturerName": "Sample Manufacturer"
>         }
>       ]
>     }
>   }
> }
> ```
> 
> What should I do ?

Hi
I faced the same issue.
Try to use nearest region for creating your lambda function.
By using mine nearest region I solved my problem. (India --> eu-west-1)
Thank you.

**Comment by AJ1326** [comment]
Hi @kartikeya-rana @mikemaas-amazon 
Did you find the solution to this problem?

**Comment by aszk** [comment]
The skill sample is for US(en-US locale). Please refer [this document](https://developer.amazon.com/en-US/docs/alexa/smarthome/develop-smart-home-skills-in-multiple-languages.html) to update your skill depending on your location. If you have further question, please contact us https://alexa.design/contactus
