### ISSUE TITLE
Not Responding correctly for some devices,  after adding more sample devices of different Interface 

### ISSUE THREAD

**Issue by SnehilChouhan** [alexa-samples/skill-sample-python-smarthome-switch#4]
I added more devices BrightnessController ,  ColorTemperatureController , ThermostatController , Speaker 
All are working perfectly and also saving correct values in Database. 
All shows correct Response in Cloudwatch. 

But for some reason Alexa does not respond correctly for ColorTemperatureController and ThermostatController 

It gives "Sorry {} device is not responding"

Please help 

Thanks

**Comment by mikemaas-amazon** [comment]
This feels like it might be an error in the code. I would dump out the incoming event and outing response of every call into your lambda.

Also, can you give examples of what utterances you are giving Alexa for the ColorTemperatureController and ThermostatController?  Something like "Alexa, make the bedroom warm white."?

**Comment by SnehilChouhan** [comment]
Yes, I am giving similar utterance.   And yes, I am checking incoming event - outing response. 

Here is one example:
Request:

`{
    "directive": {
        "header": {
            "namespace": "Alexa.ThermostatController",
            "name": "SetTargetTemperature",
            "payloadVersion": "3",
            "messageId": "09b220d8-7692-40cf-baa0-40e09be9b9ad",
            "correlationToken": "AAAAAAAAAQA6wX5dnvZtKDlqlusnBIbODAIAAAAAAABrxT97Mjl/i7kueLC4QeNYOSa9bK/Tt1dTEH+cPalWNFup9oZgoTV3K5wnShbof0QbrsLp28+4lbRCsAFrUyivvdxxgt/zE8lvQjCoI36wFRbGrRn5yFzl7YCUnbzU7CIJiOcA/HLmA+lv7PuFKvpe3escsAdKK2CLS1zJEj360XV+oR+GzG3DGZt6lhxPpN/M66W1FHU+mU0ILjwv9XQ6H03cbZHclImqv7IemcQFrRok2Mr6Y0jeC/Q2zM2giAQrUEZi5Spu2R1H6qfWUk2i/vUwPIETXozz49OQ4qT4aTh2pi5V9/z7GDcFSiOHITDyZUgPkWsJ67PdD6pP+JAnqq4qFhJf+euj3RF0rYR92vFE+8i0DHeCAxW9BZx2zla9JGoYJ8uv5ccixcUnN63rWrKY7gnTsQ99xbww4p2UPQVia62H+cDChy6glSecaOljY4lxkIES0z41cgQL/I+i3inu6AAT3hDe83HGUMg77PdaIbx+DiADbRzuu/OQt5Qj4DoFjciqO4VB27v76xURgdkyC6JJDLohprNQ89NYVF3T7oneIIgwcyG5aO8iedOj1+6mhwJPDqx+nY5vb5I9cfdVDhTrR+ILpe/t3xZaU+GpPx9ssO5sQ9W8keexNk0CedSrHlvfod6RHVXIazkWtIgiASOtME3Oo1NOA7IiL08c2aBTJZ8KYPa7aw=="
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "Atza|IwEBIDEteHfIgejcn3BOIo4PlpkPCNXyfl32xJP7YQf4CGNDRKwM-SVd-r7YYqsr5exGcmc2P_WEjCCpenu0mQgf2B0oee8748OIRgo2lOLXzq8OIYZf8mTTqshq0HwioQk6NU59cOAOs8_gMtzhHt8w94x-e39GLS_jrnHOSqMpw3X-X8HMOHi37zePE5PX0OVJVyEz1nqY931pKofm250-61hbQC4oXmiIlZcurV_EUW4J5S0hqXv8jnZUVluBzdQqHklUsds5ykPUvGpZNPBUvQktm7Y0Jf9brJUNvlZl5659fJTiqQ6lKPnI78XBiDta02eAfxgRnt9PKkKc4KdHLEIlXlUvJ70N-2vIFIkxWVLW2ewkO8U6ATallIbO782ZwJNNXaYJ8tY724gKLXiK7Dda3OnUH3a2lV5Er1l-Yq_mwTk2iSbdj2F6jsLIfuL_TzjORD3iAhaE3ltGwPdex-02zJQpQsyY-KlsxTDMoe4ag81ETLITQAlOq0D0khwR8XI"
            },
            "endpointId": "sample-heater-01",
            "cookie": {}
        },
        "payload": {
            "targetSetpoint": {
                "value": 40,
                "scale": "CELSIUS"
            }
        }
    }
}`


and Response 
`{
    "context": {
        "properties": [
            {
                "namespace": "Alexa.ThermostatController",
                "name": "HeaterTemp",
                "value": "40.0",
                "timeOfSample": "2019-07-24T15:59:09.00Z",
                "uncertaintyInMilliseconds": 0
            }
        ]
    },
    "event": {
        "header": {
            "namespace": "Alexa",
            "name": "Response",
            "messageId": "807c8cda-1485-4d78-acf5-ce04f319a9a5",
            "payloadVersion": "3",
            "correlation_token": "AAAAAAAAAQA6wX5dnvZtKDlqlusnBIbODAIAAAAAAABrxT97Mjl/i7kueLC4QeNYOSa9bK/Tt1dTEH+cPalWNFup9oZgoTV3K5wnShbof0QbrsLp28+4lbRCsAFrUyivvdxxgt/zE8lvQjCoI36wFRbGrRn5yFzl7YCUnbzU7CIJiOcA/HLmA+lv7PuFKvpe3escsAdKK2CLS1zJEj360XV+oR+GzG3DGZt6lhxPpN/M66W1FHU+mU0ILjwv9XQ6H03cbZHclImqv7IemcQFrRok2Mr6Y0jeC/Q2zM2giAQrUEZi5Spu2R1H6qfWUk2i/vUwPIETXozz49OQ4qT4aTh2pi5V9/z7GDcFSiOHITDyZUgPkWsJ67PdD6pP+JAnqq4qFhJf+euj3RF0rYR92vFE+8i0DHeCAxW9BZx2zla9JGoYJ8uv5ccixcUnN63rWrKY7gnTsQ99xbww4p2UPQVia62H+cDChy6glSecaOljY4lxkIES0z41cgQL/I+i3inu6AAT3hDe83HGUMg77PdaIbx+DiADbRzuu/OQt5Qj4DoFjciqO4VB27v76xURgdkyC6JJDLohprNQ89NYVF3T7oneIIgwcyG5aO8iedOj1+6mhwJPDqx+nY5vb5I9cfdVDhTrR+ILpe/t3xZaU+GpPx9ssO5sQ9W8keexNk0CedSrHlvfod6RHVXIazkWtIgiASOtME3Oo1NOA7IiL08c2aBTJZ8KYPa7aw=="
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "INVALID"
            },
            "endpointId": "INVALID"
        },
        "payload": {}
    }
}`


Here it shows Response correct I think,  so it does print too. 

And also saves value in database. 

But in Actual Alexa does not response correct.

**Comment by SnehilChouhan** [comment]
If anyone got any solution for this problem, please let me know

**Comment by mikemaas-amazon** [comment]
The token and endpointId of your response to Alexa need to be legitimate. You get (and store) those from the authorization grant flow. https://developer.amazon.com/docs/account-linking/configure-authorization-code-grant.html

It is a dense topic but you need authenticate/authorize and get a valid token and endpoint for communicating back to Alexa. You correctly get the request but need to go through the authorization code flow to get those placeholders marked as INVALID in the code samples and correctly send the response.

**Comment by SnehilChouhan** [comment]
Skill is going through Account linking. With token I can get user's details, so token is correct/valid. As you mentioned, token and endpointId of your response to Alexa should be legitimate, and not marked as INVALID.

Now, I did code for responding with correct token and endpointId. Here is example: 

```
{
    "context": {
        "properties": [
            {
                "namespace": "Alexa.ThermostatController",
                "name": "targetSetpointV",
                "value": "50.0",
                "timeOfSample": "2020-05-09T15:19:04.00Z",
                "uncertaintyInMilliseconds": 0
            }
        ]
    },
    "event": {
        "header": {
            "namespace": "Alexa",
            "name": "Response",
            "messageId": "1d397637-b548-499b-96d3-bcfadc0df091",
            "payloadVersion": "3",
            "correlation_token": "AAAAAAAAAQDffujOadVeL79SyEAksaJP/AEAAAAAAAD50vztMxTmuDslJiuopru3saT33Rs/Iu8SMSS/EmxjE2voc0U7yjN09J+sJfiGlz/3n3Qm3FgUo3QV9Bn/TO0P36kd3MVhUuuJotpKAjDQpdJvZh0RwQLSuPG5aC0RHpRsXlj+9/frortG+HwtIBy9C+8OPG7Kj9YUaIK/CNyl8L2idmKttwLa0HiVkPHTcrKC79k9aMjJ1TdE8NBzP602MMAvOyTb/pHs/ThJq2dPOnLqls4AYEperaTA5/3tB0HECvAp0I5D7dVU5xlDtmgY3Y2oCoMskdtvU+Hw6L2C+mKQOAg0NfUbikxtR/tuCRtSpNRaRU3FScK0fhMT8oJ7TX7KrEBSIOjT/Gji20Tu6cgXZrm3tt/i0uCNiDN6JxJ0ZGlEHQNnF5ijmGZI6qbfZ4zLTantgAJPvfXxG5yXdCkChQ+BBlKAopYjL+XA2n93cSc9fkX6DvmBa1TDwTW5sQMgI+ymqWg6+ULo83q83s3A5K/Zrh2diZi2MhdqNkgr8eBEd+5F4yhDbTTnY5akZ62kgkjJs1mf7MMbTc6wdCPFzNVbqmJC9BNYhEHHSRByI+VPtvUIukTfpxHqr/zJXLQt6HzVDKCBbHc2xcVPZlDyvzPkle3RGVjDw2eftZ7Lbj+QHhBJg/c9ONziUZmjDw1/Cpj8OhrSf1YP"
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "Atza|IwEBILFh9y_0b1y7LDFzW2KKLy9UGjsNyqsOQ81SBlzjN75lVZ1Joql6MKBBZMMOp0C0jbWLwa3nLkEIBiEECbvsH2xhekXBfcGZp2zo9vz2pa7i9xxdKNkx1EUDnnWn1ExK4hCKuowu6DrnLmFVGOdKoMQBMKlb1pYmdQewNei3GPZzV9NDy4YC3-MThmePWZ-HoJYBPtUBo8Tjnm4yUZPzWLCd4DhcthpYVab2CZdd8ocPZWd0Ccz3WIwJOhdCYLZgcnpOeEY9BCEeM8dYFcAd8xIr3Bp5txP1uzTa2WlA5QwjivD9Jgpx9HxOj7EU0zTS2DvPwUE-s0SuDNL3xsG8fnlOlsR3nIBUZqpIaDjKi-STlmNN5tKYEChSmE6GVuGZlvjvIMm0zAzqc09hOliPp-0Pm59jtygJbo0CUy4TH9dOXVvxzHWvG1vmZDQmiD2_1AeSwPQ1FcTQb4tf7SH0vuG4p5kyAZZiMYoxK_mBQjkLGVkzgu-_7WcW1wDSx7pPiXI"
            },
            "endpointId": "sample-heater-01"
        },
        "payload": {}
    }
}

```

Still on testing with Alexa device it responds same for it like earlier: "Sorry Sample Heater is not responding"

**Comment by SnehilChouhan** [comment]
In case of ThermostatController, It tells "Sorry sample heater is not responding"

In case of ColorTemperatureController, it tells "I am not quite sure what went wrong"

Example Utterance: Alexa, set sample dining room light to warm white. 

It does set proper value in database. But does not respond correct. 

Here is request:

```
{
    "directive": {
        "header": {
            "namespace": "Alexa.ColorTemperatureController",
            "name": "SetColorTemperature",
            "payloadVersion": "3",
            "messageId": "beaa5b10-6303-4f33-add7-ef8ab85c922d",
            "correlationToken": "AAAAAAAAAQDffujOadVeL79SyEAksaJP/AEAAAAAAADq7xptwYsvYy29d1AS518hX5huUPJZhIyf2U5v/zqsvACLLjGZJDJlmXSZfC+jFHilnw68fsv3b75dmnCrJTQgogeLtET5U+IkNKo48kVXaieaH0nnAWtHXFgc/iAoSxQPzCdvGpqnytqKN2Ghrh+WAjmCETMHVSH7+lsQ1ccFyQMylzlzdL8ZW+WNjvd+4hSQ65a32lCu4ETaW4sxmmY9knHTroiSL/SJy0K7Y26sIaJqF2BbTRpIcJ6A6SB4uCwR8z+z5R2+wAk9YTuLh15zB+Uygg0sjvyemHvUodqjA0jhIO0CKMjZGuQulwfgrMMmEniwXauRh3OpXUK5zbfsx9TEGK12eIkSb3ZwJRVNr9o6YZl9IWFj9Xf259u4Iep8uch600S3OPsGoSDpUsXyzPj3ttj1eb3arKOrfFwWFcJMxnjM/yZnURXWkbxtvULueI6FIP8xIyXYyyAHFhv6jnlgCly5haxPOqJQX2d5qJYqvXEj0YzHZMITbknLQOypgyMeqIqNQYamjZNYjPnZht4UO6GtC7BiJBiUhq+TvpIFOzCWvKX9GcCoEC8oV85xGsX/NL4Ph/pXPWPNlsRIvsBtnkNPLXrEvq1R2t8vvhDNplH08WfP+y8srV4R5POaTNVIR84u144PRJPOIY0VUgrq+3sQX3WEg81B"
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "Atza|IwEBIIH0xrK9y0Jtxjc8WdytRP4ll985x2PrVnnY6YwIiGbOKwK3li0u8fNF3vk8cMuOnxskJGgfQ4fVGAi0o6LGsxfvg36PPpv1JNWv2CONfGhtNcWwndhi011G1LMukRp7W4caBsk9DecW-NpbdNzfbFB8is9xQnSm81WgIJzF3SU5Z_AsJuSxqe2utC3P5hlo9Po_x9ZaG1W60h3VMtbcwQw_s9cTQ8GPPG9IYa2YhwNl8PsP5_QuvQeXUUvw_WQ4vaI0sourkUcGEXvBlzjso_kL6xPnI-v-NZiHdrQFOlz1N6PV36rhesLwIehKUZVuRaqmJgLVCoDNmm8S9PUgjxbz5QostWM1JbWrBQrOFDhf9wqRK4glo4bYawANWFzvY0tbLsrXF9S56J2gZpmwWoOWRs98nK_4GPauxxrDRkXH86MwFmBGkKvWklqGeIOvDM-kVWmtHda1h4_guo9pNeTST9OiIajsGBnsD2U1GlT8fkiJUzMnvwAYrbmlH2lmq1g"
            },
            "endpointId": "sample-dining-room-01",
            "cookie": {}
        },
        "payload": {
            "colorTemperatureInKelvin": 2200
        }
    }
}
```

And Here is Response:

```
{
    "context": {
        "properties": [
            {
                "namespace": "Alexa.ColorTemperatureController",
                "name": "SetColorTemperature",
                "value": "2200",
                "timeOfSample": "2020-05-09T16:37:18.00Z",
                "uncertaintyInMilliseconds": 0
            }
        ]
    },
    "event": {
        "header": {
            "namespace": "Alexa",
            "name": "Response",
            "messageId": "cff4af98-1e53-4e61-80d6-c98f0379101c",
            "payloadVersion": "3",
            "correlation_token": "AAAAAAAAAQDffujOadVeL79SyEAksaJP/AEAAAAAAADq7xptwYsvYy29d1AS518hX5huUPJZhIyf2U5v/zqsvACLLjGZJDJlmXSZfC+jFHilnw68fsv3b75dmnCrJTQgogeLtET5U+IkNKo48kVXaieaH0nnAWtHXFgc/iAoSxQPzCdvGpqnytqKN2Ghrh+WAjmCETMHVSH7+lsQ1ccFyQMylzlzdL8ZW+WNjvd+4hSQ65a32lCu4ETaW4sxmmY9knHTroiSL/SJy0K7Y26sIaJqF2BbTRpIcJ6A6SB4uCwR8z+z5R2+wAk9YTuLh15zB+Uygg0sjvyemHvUodqjA0jhIO0CKMjZGuQulwfgrMMmEniwXauRh3OpXUK5zbfsx9TEGK12eIkSb3ZwJRVNr9o6YZl9IWFj9Xf259u4Iep8uch600S3OPsGoSDpUsXyzPj3ttj1eb3arKOrfFwWFcJMxnjM/yZnURXWkbxtvULueI6FIP8xIyXYyyAHFhv6jnlgCly5haxPOqJQX2d5qJYqvXEj0YzHZMITbknLQOypgyMeqIqNQYamjZNYjPnZht4UO6GtC7BiJBiUhq+TvpIFOzCWvKX9GcCoEC8oV85xGsX/NL4Ph/pXPWPNlsRIvsBtnkNPLXrEvq1R2t8vvhDNplH08WfP+y8srV4R5POaTNVIR84u144PRJPOIY0VUgrq+3sQX3WEg81B"
        },
        "endpoint": {
            "scope": {
                "type": "BearerToken",
                "token": "Atza|IwEBIIH0xrK9y0Jtxjc8WdytRP4ll985x2PrVnnY6YwIiGbOKwK3li0u8fNF3vk8cMuOnxskJGgfQ4fVGAi0o6LGsxfvg36PPpv1JNWv2CONfGhtNcWwndhi011G1LMukRp7W4caBsk9DecW-NpbdNzfbFB8is9xQnSm81WgIJzF3SU5Z_AsJuSxqe2utC3P5hlo9Po_x9ZaG1W60h3VMtbcwQw_s9cTQ8GPPG9IYa2YhwNl8PsP5_QuvQeXUUvw_WQ4vaI0sourkUcGEXvBlzjso_kL6xPnI-v-NZiHdrQFOlz1N6PV36rhesLwIehKUZVuRaqmJgLVCoDNmm8S9PUgjxbz5QostWM1JbWrBQrOFDhf9wqRK4glo4bYawANWFzvY0tbLsrXF9S56J2gZpmwWoOWRs98nK_4GPauxxrDRkXH86MwFmBGkKvWklqGeIOvDM-kVWmtHda1h4_guo9pNeTST9OiIajsGBnsD2U1GlT8fkiJUzMnvwAYrbmlH2lmq1g"
            },
            "endpointId": "sample-dining-room-01"
        },
        "payload": {}
    }
}
```

**Comment by aszk** [comment]
Could you use https://alexa.design/contactus for further assistance? This sample doesn't support ColorTemperatureController or ThermostatController.
