### ISSUE TITLE
Devices not discovering anymore for new test users 

### ISSUE THREAD

**Issue by SnehilChouhan** [alexa-samples/skill-sample-python-smarthome-switch#5]
Few months ago, I had demo Smart Home skill working, in which user can link account,  some types of demo devices were discovering and control on it. 
Currently when I discover devices, it tells 'No new devices found'.  It does not show demo/virtual devices in app also. 
Earlier it was working. 

Response to discovery interface is same as earlier. 

Here is example request:
`{

    "directive": {

        "header": {

            "namespace": "Alexa.Discovery",
            "name": "Discover",
            "payloadVersion": "3",
            "messageId": "90939566-c7a7-4195-93ad-1a97834a3ab7"
        },

        "payload": {

            "scope": {

                "type": "BearerToken",
                "token": "Atza|IwEBIAjCr4kpR6T2B1cEdIfvCCxQmwwRBn28bC-pMOT0gmphXVQ1RR7cpuuuyX5Zd3nIKc77VmqeBw1FHP7m2LsOloqErzjHiliicy8pvtlJ1jvUxetVarUj8LvL_e9cT39CTqyERCJLzOKicZsW6z_679I7re1MOIOragx2T6yvrDRUUxo_O3KiflwMVZe87QZqZqURydYIZeCdi1S9SwmqCgPMKBxmsMfRq1vQIFP2RLe63C8VqlkTLvcBsWmVfSNE8SFwDpJuZI3Q2tFy2q2yOgBbLdL1oTd_EK8-mh813fsrzD1GcFixrTKrUgyAZulOmAe7jqB4-4E9eZbqbZ3Iyx1sPX0ltGc1KFjcOs2nZSVnpg"
            }

        }

    }

}
`

And here is Response:

`{

    "event": {

        "header": {
            "namespace": "Alexa.Discovery",
            "name": "Discover.Response",
            "messageId": "288fc958-b7c0-4782-840b-01a40c06f94d",
            "payloadVersion": "3"
        },

        "payload": {

            "endpoints": [
                {
                    "capabilities": [

                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa",
                            "version": "3"
                        },
                        {

                            "type": "AlexaInterface",
                            "interface": "Alexa.PowerController",
                            "version": "3",
                            "properties": {

                                "supported": [
                                    {
                                        "name": "powerState"
                                    }
                                ],
                                "proactivelyReported": false,
                                "retrievable": false
                            }

                        }
                    ],

                    "description": "Sample Endpoint Description",
                    "displayCategories": [
                        "OTHER"
                    ],

                    "endpoint_id": "sample-switch-01",
                    "friendlyName": "Sample Switch",
                    "manufacturerName": "Sample Manufacturer"
                },

                {
                    "capabilities": [

                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa",
                            "version": "3"
                        },
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa.BrightnessController",
                            "version": "3",
                            "properties": {
                                "supported": [
                                    {
                                        "name": "brightness"
                                    }

                                ],
                                "proactivelyReported": false,
                                "retrievable": false
                            }
                        }

                    ],

                    "description": "Sample Endpoint Description",
                    "displayCategories": [
                        "OTHER"
                    ],

                    "endpoint_id": "sample-brightness-01",
                    "friendlyName": "Sample Brightness Bulb",
                    "manufacturerName": "Sample Manufacturer"
                },
                {

                    "capabilities": [
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa",
                            "version": "3"
                        },

                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa.ColorTemperatureController",
                            "version": "3",
                            "properties": {
                                "supported": [
                                    {

                                        "name": "SetColorTemperature"
                                    }
                                ],
                                "proactivelyReported": false,
                                "retrievable": false
                            }
                        }

                    ],
                    "description": "Sample Endpoint Description",
                    "displayCategories": [
                        "OTHER"
                    ],

                    "endpoint_id": "sample-dining-room-01",
                    "friendlyName": "Sample Dining Room",
                    "manufacturerName": "Sample Manufacturer"
                },
                {

                    "capabilities": [
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa",
                            "version": "3"
                        },
                        {

                            "type": "AlexaInterface",
                            "interface": "Alexa.ThermostatController",
                            "version": "3",
                            "properties": {
                                "supported": [
                                    {
                                        "name": "targetSetpoint"
                                    }
                                ],

                                "proactivelyReported": false,
                                "retrievable": false
                            }
                        }
                    ],
                    "description": "Sample Endpoint Description",
                    "displayCategories": [
                        "OTHER"
                    ],

                    "endpoint_id": "sample-heater-01",
                    "friendlyName": "Sample Heater",
                    "manufacturerName": "Sample Manufacturer"
                },
                {
                    "capabilities": [
                        {
                            "type": "AlexaInterface",
                            "interface": "Alexa",
                            "version": "3"
                        },
                        {

                            "type": "AlexaInterface",
                            "interface": "Alexa.Speaker",
                            "version": "3",
                            "properties": {
                                "supported": [
                                    {
                                        "name": "SetVolume"
                                    },
                                    {
                                        "name": "SetMute"
                                    }
                                ],

                                "proactivelyReported": false,
                                "retrievable": false
                            }
                        }
                    ],
                    "description": "Sample Endpoint Description",
                    "displayCategories": [
                        "OTHER"
                    ],

                    "endpoint_id": "sample-speaker-01",
                    "friendlyName": "Sample Speaker",
                    "manufacturerName": "Sample Manufacturer"
                }
            ]
        }

    }
}`

Please help,  Does it have any relation to different users, database etc?

Thank you

**Comment by ianuj03** [comment]
Same here, after execution the Sample Switch is not added to my device section. And hence, as the consequence if I try testing it says _Sorry, I didn't find a device named sample switch_

**Comment by yuriboeira11tx** [comment]
Same issue.

**Comment by yiotix** [comment]
I had the same issue. According to the docs, only US-East 1 works for discovery. Recreating the lambda in the correct region fixed this issue for me.

**Comment by aszk** [comment]
Like yiotix mentioned it might be related to the user's location. Please use [alexa.design/contactus](https://alexa.design/contactus) for more help. We might need sensitive information to solve your issue.
