### ISSUE TITLE
'instance' field is missing in create_context_property while required for Alexa.RangeController

### ISSUE THREAD

**Issue by poltorakvs** [alexa-samples/skill-sample-python-smarthome-switch#7]
Alexa.RangeController should contain an 'instance' field. See https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-rangecontroller.html#statereport-response-event-example

Please add it to create_context_property function
https://github.com/alexa-samples/skill-sample-python-smarthome-switch/blob/30f7b7effa531de5e100f1323494bb4ed5dfbdf3/lambda/smarthome/alexa/skills/smarthome/alexa_response.py#L70

**Comment by aszk** [comment]
This sample code is a sample Alexa Smart Home skill using Python that creates and controls a virtual sample switch that responds to ON/OFF commands. Hence we cover only PowerController.
