### ISSUE TITLE
I followed the tutorial but at the end the last testing dont result in ok alexa only play a sound… 

### ISSUE THREAD

**Issue by sebosfato** [alexa-samples/skill-sample-python-smarthome-switch#9]
I followed the tutorial but at the end the last testing dont result in ok alexa only play a sound… 

the first test on the lambda function works… however alexa turn on sample switch dont give an ok … and on the log it gives the following error 

{
    "PowerController": [
        {
            "name": "DevRe_1.0",
            "status": "ERROR",
            "error": {
                "message": "Test Case Execution Error."
            }
        },
        {
            "name": "DevRe_1.1",
            "status": "ERROR",
            "error": {
                "message": "Test Case Execution Error."
            }
        }
    ]
}

Any idea how to overcome?

**Comment by aszk** [comment]
The short answer is this sample can't pass the test tool. To pass automation test on Alexa Developer Console, your device has to be retrievable true and the skill needs to respond correct [stateReport](https://developer.amazon.com/en-US/docs/alexa/device-apis/alexa-statereport.html). This sample doesn't respond stateReport and the virtual device uses retrievable false.
